import { siteConfig } from "@/config/site"
import { Icons } from "@/components/Icons"

export function SiteFooter() {
  return (
    <div className="container bottom-0 w-full flex flex-col justify-center items-center gap-2 py-4 border-t border-t-slate-200 dark:border-t-slate-700 sm:justify-between sm:flex-row sm:gap-6">
      <Icons.logo className="w-4 h-4 sm:h-6 sm:w-6" />
      <p className="text-justify text-xs leading-loose text-slate-600 dark:text-slate-400">
        Built by{" "}
        <a
          href={siteConfig.links.linkedin}
          target="_blank"
          rel="noreferrer"
          className="font-medium underline underline-offset-4"
        >
          Adam Ksiazek
        </a>
        . Images generated by{" "}
        <a
          href={siteConfig.links.midjourney}
          target="_blank"
          rel="noreferrer"
          className="font-medium underline underline-offset-4"
        >
          Midjourney
        </a>
        . Design inspired by{" "}
        <a
          href={"https://github.com/shadcn"}
          target="_blank"
          rel="noreferrer"
          className="font-medium underline underline-offset-4"
        >
          Shadcn
        </a>
        . Quizander is not endorsed or supported directly or indirectly with
        Warner Bros. Entertainment, JK Rowling, Wizarding World Digital, or any
        of the official Harry Potter trademark/right holders.
      </p>
    </div>
  )
}
