import { siteConfig } from "@/config/site"
import { Icons } from "@/components/Icons"

export function SiteFooter() {
  return (
    <div className="bottom-0 w-full flex flex-col border-t border-t-dark-200 dark:border-t-dark-400 dark:bg-dark-600">
      <div className="container flex flex-col justify-center items-center gap-2 py-4 sm:justify-between md:flex-row sm:gap-4">
        <Icons.logo className="w-4 h-4 md:h-8 md:w-8 text-dark-400 dark:text-dark-200" />
        <p className="text-justify text-xs leading-loose text-dark-400 dark:text-dark-200">
          Built by{" "}
          <a
            href={siteConfig.links.linkedin}
            target="_blank"
            rel="noreferrer"
            className="font-medium underline underline-offset-4"
          >
            Adam Ksiazek
          </a>
          . Images generated by{" "}
          <a
            href={siteConfig.links.midjourney}
            target="_blank"
            rel="noreferrer"
            className="font-medium underline underline-offset-4"
          >
            Midjourney
          </a>
          . Design inspired by{" "}
          <a
            href={"https://github.com/shadcn"}
            target="_blank"
            rel="noreferrer"
            className="font-medium underline underline-offset-4"
          >
            Shadcn
          </a>
          . Quizander is not endorsed or supported directly or indirectly with
          Warner Bros. Entertainment, JK Rowling, Wizarding World Digital, or
          any of the official Harry Potter trademark/right holders.
        </p>
      </div>
    </div>
  )
}
